apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-role-binding
  namespace: ers
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: ers
roleRef:
  kind: Role
  name: tiller-role 
  apiGroup: rbac.authorization.k8s.io